### ISSUE TITLE
How to cite this repo?

### ISSUE THREAD

**Issue by kowshikthopalli** [arundo/tsaug#16]
Basically the title.
I used this awesome repo and I would like to cite this repo in my paper. How to do it.
If you could provide a bibtex entry that will be great

**Comment by tailaiw** [comment]
Thank you for using `tsaug`. You may cite the following paper (the original work that we created the package for):

Wen, Tailai, and Roy Keyes. "Time series anomaly detection using convolutional neural networks and transfer learning." arXiv preprint arXiv:1905.13628 (2019).

**Comment by kowshikthopalli** [comment]
Thank you. will do that.
