### ISSUE TITLE
can't find the deepad python package

### ISSUE THREAD

**Issue by xsqian** [arundo/tsaug#2]
In the quickstart notebook https://github.com/arundo/tsaug/blob/master/docs/quickstart.ipynb
`from deepad.visualization import plot`
where can you find the deepad package to install?

**Comment by tailaiw** [comment]
Thanks for raising this. It is a plotting function that we used in a private package called `deepad` (in fact `tsaug` was originally a module of that package and we decided to open-source it). I will discuss with the core developers of that package to see if we may make the plotting function available, but please consider the quickstart notebook just for the demo purpose and not runnable for now. In fact, you may notice that the cell you pointed out is not visible in the documentation. 

I have removed the cell from the notebook with #3
